### ISSUE TITLE
report() fails outside of a git repo.

### ISSUE THREAD

**Issue by wongl01** [Julia-Tempering/InferenceReport.jl#28]
When calling report() with render=true outside of a git repo, the following error occurs:
![image](https://github.com/Julia-Tempering/InferenceReport.jl/assets/90303797/33f73d0b-e11a-4705-90a4-2f31718fac30)
Using git init to create an empty repo then committing something to it causes report() to work as intended.

**Comment by alexandrebouchard** [comment]
Good catch! Do you want to try creating a PR for fixing this? @nikola-sur can you add him to the organization. Then Lucas this would involve creating a branch, making the change and creating a PR. If you need any help along the way, ping us on slack!

**Comment by nikola-sur** [comment]
@wongl01 I just sent you an invite to join the organization.

**Comment by wongl01** [comment]
Thanks Nikola, I'll get started on trying to fix that today.

**Comment by miguelbiron** [comment]
Closed by #29
